apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/necipulusoy/gitops.git'
    targetRevision: main
    # path to the directory containing the application manifests
    path: system/dev
    directory:
      recurse: true # finds all yaml files in subdirectories
      exclude: '{*RootArgoApp.yaml,*RootArgoApp.yml}' # do not manage root apps
      # include: '*.yaml'
  destination:
    name: "in-cluster"
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true