apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/necipulusoy/applications.git  # kendi repounun URL'si
    targetRevision: HEAD
    path: .   # ← root dizin 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
